---
title: "Initial analysis of pleiotropy test results"
author: "Frederick Boehm"
date: "6/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
path_to_results <- "~/Box Sync/attie/keller-hotspots/results"
```

First, how many results files do I have?

Recall that I submitted 10332 (Chr 11), 1768 (Chr 13), 7644 (Chr 2), 6734 (Chr 5), and 8979 (Chr 7) jobs.

Now, let's count the files in our subdirectories.

```{bash}
cd ~/Box\ Sync/attie/keller-hotspots/results/
cd pvl-run-9901; ls | wc
cd ../pvl-run-9911; ls | wc
cd ../pvl-run-9921; ls | wc
cd ../pvl-run-9931; ls | wc
cd ../pvl-run-9941; ls | wc
```







```{r}
library(tidyverse)
```




```{r}
library(qtl2chtc)
```

```{r}
find_missing_jobs(DIR = "~/Box Sync/attie/keller-hotspots/results/pvl-run-9901", njobs = 6734, outfile = "~/Box Sync/attie/keller-hotspots/submit_files/run9901-bad")
find_missing_jobs(DIR = "~/Box Sync/attie/keller-hotspots/results/pvl-run-9911", njobs = 8979, outfile = "~/Box Sync/attie/keller-hotspots/submit_files/run9911-bad")
find_missing_jobs(DIR = "~/Box Sync/attie/keller-hotspots/results/pvl-run-9921", njobs = 10332, outfile = "~/Box Sync/attie/keller-hotspots/submit_files/run9921-bad")
```

```{r}

```


