# Chr `r hot_chr`


```{r}
hot_lower <- hot_mid - 2
hot_upper <- hot_mid + 2
fp <- paste0("Chr", hot_chr, "-")
knitr::opts_chunk$set(fig.path = here("analysis", "figures", fp))
```


```{r}
pleio_mixed_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", hot_chr, "_pleio.rds")))
pleio_local_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", hot_chr, "_pleio_local.rds")))
pleio_nonlocal_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", hot_chr, "_pleio_nonlocal.rds")))
med_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", hot_chr, "_mediations.rds")))
```










```{r}
local_annot <- lod_peaks %>%
  filter(chrom == hot_chr, pos <= hot_upper, pos >= hot_lower) %>%
  left_join(y = annots, by = c("annot.id" = "gene_id")) %>%
  filter(!duplicated(annot.id)) %>%
  filter(lod >= ult) %>%
  mutate(local_tx = chr == hot_chr) %>%
  filter(local_tx)
```


```{r}
nonlocal_annot <- lod_peaks %>%
  filter(chrom == hot_chr, pos <= hot_upper, pos >= hot_lower) %>%
  inner_join(y = annots, by = c("annot.id" = "gene_id")) %>%
  filter(!duplicated(annot.id)) %>%
  filter(lod >= 7.18) %>%
  mutate(local_tx = chr == hot_chr) %>%
  filter(!local_tx) %>%
  filter(!is.na(hotspot))
```



```{r}
local_annot2 <- local_annot %>%
  filter(middle <= hot_upper + 1, middle >= hot_lower - 1) %>% 
  arrange(desc(lod))
```


```{r}
hot_local <- expr[, colnames(expr) %in% local_annot2$annot.id]
hot_nonlocal <- expr[, colnames(expr) %in% nonlocal_annot$annot.id]
nnonlocal <- nrow(nonlocal_annot)
nlocal <- nrow(local_annot2)
```


```{r, message=FALSE, warning = FALSE}
med_tib <- med_list %>%
  purrr::map(bind_rows) %>%
  bind_rows() %>%
  as_tibble() %>%
  rename(lod_without_med = lod_no_med, lod_with_med = lod_med) %>%
  mutate(lod_diff = lod_without_med - lod_with_med, lod_diff_proportion = lod_diff / lod_without_med) %>%
  left_join(local_annot2, by = c("local_gene_id" = "annot.id")) %>%
  left_join(nonlocal_annot, by = c("nonlocal_gene_id" = "annot.id")) %>%
  dplyr::select(symbol.x, symbol.y, lod_without_med, lod_with_med, lod_diff, lod_diff_proportion, local_gene_id, nonlocal_gene_id) %>%
  rename(local_symbol = symbol.x, nonlocal_symbol = symbol.y) %>%
  filter(!is.na(local_symbol))
```


```{r}
hot_annot <- local_annot2 %>%
  bind_rows(nonlocal_annot) %>%
  dplyr::select(annot.id, symbol)
pleio_tib <- pleio_mixed_list %>%
  purrr::map(.f = function(x) rename(x, gene1_id = local_gene_id, gene2_id = nonlocal_gene_id)) %>%
  c(pleio_local_list, pleio_nonlocal_list) %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(hot_annot, by = c("gene1_id" = "annot.id")) %>%
  rename(gene1_symbol = symbol) %>%
  inner_join(hot_annot, by = c("gene2_id" = "annot.id")) %>%
  rename(gene2_symbol = symbol) %>%
  dplyr::select(gene1_symbol, gene2_symbol, pleiotropy_lod)
```


```{r}
pm <- pleio_tib %>%
  tibble_to_matrix(symmetric = TRUE)
```


```{r}
p <- pleio_mixed_list %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(med_tib, by = c("local_gene_id", "nonlocal_gene_id")) %>%
  dplyr::select(local_symbol, nonlocal_symbol, pleiotropy_lod, lod_diff, lod_diff_proportion, lod_without_med, lod_with_med, filename, nonlocal_gene_id, local_gene_id) %>%
  ggplot() + geom_point(mapping = aes(x = pleiotropy_lod, y = lod_diff, colour = local_symbol == keller_mediator, nonlocal = nonlocal_symbol, local = local_symbol), size = 0.05) + theme(legend.position = "none") + xlab("Pleiotropy LOD") + ylab("Mediation LOD difference")
fnsvg <- paste0("Chr", hot_chr, "_scatter.svg")
fnpdf <- paste0("Chr", hot_chr, "_scatter.pdf")
ggsave(plot = p, filename = here("analysis", "figures", fnsvg))
ggsave(plot = p, filename = here("analysis", "figures", fnpdf))
plotly::ggplotly(p)
```






```{r, fig.height = ceiling(nlocal / 2)}
foo <- pleio_mixed_list %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(med_tib, by = c("local_gene_id", "nonlocal_gene_id")) %>%
  dplyr::select(local_symbol, nonlocal_symbol, pleiotropy_lod, lod_diff, lod_diff_proportion, lod_without_med, lod_with_med, filename, nonlocal_gene_id, local_gene_id)
p <- foo %>%
  ggplot() +
  geom_point(mapping = aes(x = pleiotropy_lod, y = lod_diff, colour = nonlocal_symbol), size = 0.1) +
  facet_wrap(. ~ local_symbol, nrow = ceiling(nlocal / 2), ncol = 2) +
  broman::karl_theme(strip.placement = "inside") +
  theme(legend.position = "none") +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
) +
  xlab("Pleiotropy LOD") +
  ylab("Mediation LOD difference") +
  geom_text(aes(x = 1, y = 1, label = local_symbol), inherit.aes=FALSE)

fnsvg <- paste0("Chr", hot_chr, "_scatter-panel.svg")
fnpdf <- paste0("Chr", hot_chr, "_scatter-panel.pdf")
ggsave(p, filename = here("analysis", "figures", fnsvg), height = ceiling(nlocal / 2))
ggsave(p, filename = here("analysis", "figures", fnpdf), height = ceiling(nlocal / 2))
plotly::ggplotly(p)
```

```{r, eval = FALSE}
# put in multiple figures, if there are many local traits
n_figs <- 1 + nlocal %/% 18 # 18 is the number of panels per page in pdf
n_last <- nlocal %% 18 # number of panels on last figure
max_pleio_lod <- max(foo$pleiotropy_lod)
max_med_lod_difference <- max(foo$lod_diff)
min_med_lod_difference <- min(foo$lod_diff)

for (i in 1:n_figs){
  n_panels <- 18 * (i < n_figs) + n_last * (i == n_figs)
  foo %>%
    filter(local_symbol %in% local_annot2$symbol[((i - 1) * 18 + 1): (18 * i)]) %>%
    ggplot() +
      geom_point(mapping = aes(x = pleiotropy_lod, y = lod_diff, colour = nonlocal_symbol), size = 0.1) +
      facet_wrap(. ~ local_symbol, nrow = ceiling(n_panels / 2), ncol = 2) +
      broman::karl_theme() +
      theme(legend.position = "none") +
      theme(
        strip.background = element_blank(),
        strip.text.x = element_blank()
    ) +
      xlab("Pleiotropy LOD") + xlim(c(0, max_pleio_lod)) + ylim(c(min_med_lod_difference, max_med_lod_difference)) +
      ylab("Mediation LOD difference") +
      geom_text(size = 2, aes(x = max_pleio_lod / 2, y = 2 * max_med_lod_difference / 3, label = local_symbol), inherit.aes=FALSE)
  fnsvg <- paste0("Chr", hot_chr, "_scatter-panel", i, ".svg")
  fnpdf <- paste0("Chr", hot_chr, "_scatter-panel", i, ".pdf")
  ggsave(filename = here("analysis", "figures", fnsvg), height = ceiling(n_panels / 2))
  ggsave(filename = here("analysis", "figures", fnpdf), height = ceiling(n_panels / 2))
}
```




```{r}
scols1 <- 1L + (rownames(pm) %in% local_annot2$symbol)
scols2 <- rownames(pm) %in% (med_tib %>% filter(local_symbol == keller_mediator, lod_diff > 1.5))$nonlocal_symbol
```


```{r}
# order the nonlocal traits first
## indicator for being a nonlocal trait
indic_nonlocal <- rownames(pm) %in% nonlocal_annot$symbol
# define ord_nonlocal
ord_nonlocal <- pm[indic_nonlocal, indic_nonlocal] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendextend::seriate_dendrogram(dist(pm[indic_nonlocal, indic_nonlocal])) %>%
  order.dendrogram()
rn_nonlocal <- rownames(pm[indic_nonlocal, indic_nonlocal][ord_nonlocal, ord_nonlocal])
# define ord_local
ord_local<- pm[!indic_nonlocal, !indic_nonlocal] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendextend::seriate_dendrogram(dist(pm[!indic_nonlocal, !indic_nonlocal])) %>%
  order.dendrogram()
rn_local <- rownames(pm[!indic_nonlocal, !indic_nonlocal][ord_local, ord_local])
rn <- c(rn_nonlocal, rn_local)
```


```{r}
scols_extra <- purrr::map(.x = local_annot2$symbol,
                          .f = function(x) {rownames(pm) %in% (med_tib %>% filter(local_symbol == x, lod_diff > 1.5))$nonlocal_symbol}
) %>%
  bind_cols() %>%
  (function(x){colnames(x) <- local_annot2$symbol; x}) %>%
  mutate(local = scols1)
```


```{r}
n_med_tr <- 4 # arbitrary threshold for number of mediated traits per local
# only those local traits with n_med_tr or more mediated nonlocal traits 
# appear as annotation columns in the heatmap
n_med_per_local <- med_tib %>%
  group_by(local_symbol) %>%
  filter(lod_diff > 1.5) %>%
  count() %>%
  filter(n >= n_med_tr)
n_med_per_local %>%
  arrange(desc(n)) %>%
  knitr::kable()

scols_pre <- scols_extra %>%
  dplyr::select(n_med_per_local$local_symbol)
# get ordering for columns of scols_pre
col_order <- scols_pre %>%
  t() %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendextend::seriate_dendrogram(dist(t(scols_pre))) %>%
  order.dendrogram()
scols <- scols_pre[ , col_order] %>%
  mutate(local = scols1)
fnhtml <- here("analysis", "figures", paste0("Chr", hot_chr, "hm.html"))
```



```{r}
ord <- match(rn, rownames(pm))

(p <- pm[ord, ord] %>%
  apply(FUN = trunc2, MARGIN = 2, threshold = 5) %>%
  heatmaply(Rowv = FALSE,
            Colv = FALSE,
            cexRow = 0.2,
            cexCol = 0.2,
            symm = TRUE,
            row_side_colors = scols[ord, ],
            col_side_colors = tibble(local = scols1[ord]),
            limits = c(0, 5)
            ) %>%
  hide_guides()
)
fnpdf <- here("analysis", "figures", paste0("Chr", hot_chr, "hm.pdf"))
htmlwidgets::saveWidget(widget = p, 
                        file = fnhtml
                        )
```

```{r eval = FALSE}
webshot::webshot(url = fnhtml,
                 file = fnpdf,
                 cliprect = "viewport"
                 )
```




```{r}
bar <- foo %>%
  filter(local_symbol == keller_mediator)

p <- tibble(nonlocal_symbol = rownames(pm[indic_nonlocal, indic_nonlocal])[ord_nonlocal], index = 1:length(nonlocal_symbol)) %>%
  inner_join(bar, by = "nonlocal_symbol") %>% 
  left_join(nonlocal_annot, by = c("nonlocal_symbol" = "symbol")) %>%
  ggplot() + geom_point(aes(y = pos, x = index, color = lod_diff > 1.5, nonlocal = nonlocal_symbol, lod_diff = lod_diff)) 

ggplotly(p)
```

