## Results

We studied five expression trait hotspots in pancreatic islets from 378 Diversity Outbred mice [@keller2018genetic]. Scatter plots of 
pleiotropy test statistic against mediation LOD difference for local - nonlocal trait pairs reveal 
some similarities for the five hotspots. All five scatter plots have few, if any, points in the upper 
right quadrant. This tells us that local-nonlocal trait pairs may have either high pleiotropy test 
statistics or high mediation LOD differences, but not both.

Examinating the ranges of pleiotropy test statistics within a hotspot also informs our conclusions. 
Some hotspots have maximum pleiotropy test statistics under 6 (Figure \@ref(fig:scatter-7)), while 
other hotspots have local-nonlocal pairs with pleiotropy test statistics over 15 (Figure 
\@ref(fig:scatter-2)). 

Some hotspot scatter plots show points with both high pleiotropy test statistics and high mediation 
LOD differences. Closer investigation of these points reveals that, for a given hotspot, they 
include a single local trait. For example, multiple pairs with local trait *Tmem130* have high 
mediation LOD differences and high pleiotropy test statistics. This may indicate that our QTL scan 
region was too narrow to encompass the entirety of the *Tmem130* peak.

