## Chr {{hot_chr}}


```{r, def-{{hot_chr}}}
hot_lower <- {{hot_mid}} - 2
hot_upper <- {{hot_mid}} + 2
```


```{r, readRDS-{{hot_chr}}}
pleio_mixed_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", {{hot_chr}}, "_pleio.rds")))
pleio_local_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", {{hot_chr}}, "_pleio_local.rds")))
pleio_nonlocal_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", {{hot_chr}}, "_pleio_nonlocal.rds")))
med_list <- readRDS(here("analysis", "data", "derived_data", paste0("Chr", {{hot_chr}}, "_mediations.rds")))
```










```{r, define_local_annot-{{hot_chr}}}
local_annot <- lod_peaks %>%
  filter(chrom == {{hot_chr}}, pos <= hot_upper, pos >= hot_lower) %>%
  left_join(y = annots, by = c("annot.id" = "gene_id")) %>%
  filter(!duplicated(annot.id)) %>%
  filter(lod >= ult) %>%
  mutate(local_tx = chr == {{hot_chr}}) %>%
  filter(local_tx)
```


```{r, define_nonlocal_annot-{{hot_chr}}}
nonlocal_annot <- lod_peaks %>%
  filter(chrom == {{hot_chr}}, pos <= hot_upper, pos >= hot_lower) %>%
  inner_join(y = annots, by = c("annot.id" = "gene_id")) %>%
  filter(!duplicated(annot.id)) %>%
  filter(lod >= 7.18) %>%
  mutate(local_tx = chr == {{hot_chr}}) %>%
  filter(!local_tx) %>%
  filter(!is.na(hotspot))
```



```{r, local_annot2-{{hot_chr}}}
local_annot2 <- local_annot %>%
  filter(middle <= hot_upper, middle >= hot_lower) %>% 
  arrange(desc(lod))
```


```{r hot_expr-{{hot_chr}}}
hot_local <- expr[, colnames(expr) %in% local_annot2$annot.id]
hot_nonlocal <- expr[, colnames(expr) %in% nonlocal_annot$annot.id]
nnonlocal <- nrow(nonlocal_annot)
nlocal <- nrow(local_annot2)
```


```{r, med_tib-{{hot_chr}}, message=FALSE, warning = FALSE}
med_tib <- med_list %>%
  purrr::map(bind_rows) %>%
  bind_rows() %>%
  as_tibble() %>%
  rename(lod_without_med = lod_no_med, lod_with_med = lod_med) %>%
  mutate(lod_diff = lod_without_med - lod_with_med, lod_diff_proportion = lod_diff / lod_without_med) %>%
  left_join(local_annot2, by = c("local_gene_id" = "annot.id")) %>%
  left_join(nonlocal_annot, by = c("nonlocal_gene_id" = "annot.id")) %>%
  dplyr::select(symbol.x, symbol.y, lod_without_med, lod_with_med, lod_diff, lod_diff_proportion, local_gene_id, nonlocal_gene_id) %>%
  rename(local_symbol = symbol.x, nonlocal_symbol = symbol.y) %>%
  filter(!is.na(local_symbol))
```


```{r, hot_annot-{{hot_chr}}}
hot_annot <- local_annot2 %>%
  bind_rows(nonlocal_annot) %>%
  dplyr::select(annot.id, symbol)
pleio_tib <- pleio_mixed_list %>%
  purrr::map(.f = function(x) rename(x, gene1_id = local_gene_id, gene2_id = nonlocal_gene_id)) %>%
  c(pleio_local_list, pleio_nonlocal_list) %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(hot_annot, by = c("gene1_id" = "annot.id")) %>%
  rename(gene1_symbol = symbol) %>%
  inner_join(hot_annot, by = c("gene2_id" = "annot.id")) %>%
  rename(gene2_symbol = symbol) %>%
  dplyr::select(gene1_symbol, gene2_symbol, pleiotropy_lod)
```


```{r pm-{{hot_chr}}}
pm <- pleio_tib %>%
  arrange(gene1_symbol, gene2_symbol) %>%
  tibble_to_matrix(symmetric = TRUE)
```


```{r, scatter-{{hot_chr}}, fig.cap="Pleiotropy test statistic vs. mediation LOD difference for Chr {{hot_chr}} hotspot."}
p <- pleio_mixed_list %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(med_tib, by = c("local_gene_id", "nonlocal_gene_id")) %>%
  dplyr::select(local_symbol, nonlocal_symbol, pleiotropy_lod, lod_diff, lod_diff_proportion, lod_without_med, lod_with_med, filename, nonlocal_gene_id, local_gene_id) %>%
  ggplot() + geom_point(mapping = aes(x = pleiotropy_lod, y = lod_diff, colour = local_symbol == "{{keller_mediator}}", nonlocal = nonlocal_symbol, local = local_symbol), size = 0.05) + theme(legend.position = "none") + xlab("Pleiotropy LOD") + ylab("Mediation LOD difference")
plotly::ggplotly(p)
```






```{r, scatter-by-local-{{hot_chr}}, fig.height = ceiling(nlocal / 2), fig.cap="Pleiotropy test statistic vs. mediation LOD difference by local expression trait for Chr {{hot_chr}} hotspot."}
foo <- pleio_mixed_list %>%
  bind_rows() %>%
  rename(pleiotropy_lod = lod) %>%
  inner_join(med_tib, by = c("local_gene_id", "nonlocal_gene_id")) %>%
  dplyr::select(local_symbol, nonlocal_symbol, pleiotropy_lod, lod_diff, lod_diff_proportion, lod_without_med, lod_with_med, filename, nonlocal_gene_id, local_gene_id)
p <- foo %>%
  ggplot() +
  geom_point(mapping = aes(x = pleiotropy_lod, y = lod_diff, colour = nonlocal_symbol), size = 0.1) +
  facet_wrap(. ~ local_symbol, nrow = ceiling(nlocal / 2), ncol = 2) +
  broman::karl_theme(strip.placement = "inside") +
  theme(legend.position = "none") +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
) +
  xlab("Pleiotropy LOD") +
  ylab("Mediation LOD difference") +
  geom_text(aes(x = max(foo$pleiotropy_lod), y = 1, label = local_symbol), inherit.aes=FALSE)
plotly::ggplotly(p)
```


```{r, scols-{{hot_chr}}}
scols1 <- tibble(local = 1L + (rownames(pm) %in% local_annot2$symbol), 
                 symbol = rownames(pm), 
                 mediated_by_keller_mediator = rownames(pm) %in% (med_tib %>% filter(local_symbol == "{{keller_mediator}}", lod_diff > 1.5))$nonlocal_symbol
                 )
```


```{r, ordering-{{hot_chr}}}
# order the nonlocal traits first
## indicator for being a nonlocal trait
indic_nonlocal <- rownames(pm) %in% nonlocal_annot$symbol
# define ord_nonlocal
ord_nonlocal <- pm[indic_nonlocal, ] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendextend::seriate_dendrogram(dist(pm[indic_nonlocal, ])) %>%
  order.dendrogram()
rn_nonlocal <- rownames(pm[indic_nonlocal, ][ord_nonlocal, ])
# define ord_local
ord_local<- pm[!indic_nonlocal, ] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendextend::seriate_dendrogram(dist(pm[!indic_nonlocal, ])) %>%
  order.dendrogram()
rn_local <- rownames(pm[!indic_nonlocal, ][ord_local, ])
rn <- c(rn_nonlocal, rn_local) # order for dendrogram
```



```{r, scols-peak-position-{{hot_chr}}}

binning <- local_nonlocal_annot %>%
  dplyr::select(symbol, pos, lod) %>%
  mutate(bin = unlist(pos) %>%
           map(.f = function(x) {x %>% 
               bin_peak_position(breaks = hot_lower + (1:9) * 0.4) %>%
               binarize_bin_number(total_number_of_bins = 10L)
             })
  ) %>%
  listcol_to_cols(list_column = quo(bin), another_column = quo(symbol))
```



```{r, scan1-{{hot_chr}}}
fn <- here::here("analysis", "data", "derived_data", "Chr{{hot_chr}}_scan1_out.rds")
if (file.exists(fn)) {
  s1out <- readRDS(fn)
} else {
  s1out <- qtl2::scan1(genoprobs = probs, 
                       pheno = cbind(hot_local, hot_nonlocal), 
                       kinship = K[["{{hot_chr}}"]], 
                       addcovar = covar, 
                       reml = TRUE, 
                       cores = 7
                       )
  saveRDS(s1out, fn)
}
```



```{r allele-effects-{{hot_chr}}}
fn <- here::here("analysis", "data", "derived_data", "Chr{{hot_chr}}_scan1coef_out.rds")
if (file.exists(fn)) {
  s1coef_out <- readRDS(fn)
} else {
s1coef_out <- purrr::map(.x = as_tibble(cbind(hot_local, hot_nonlocal)), 
           .f = function(pheno) {
             ph <- as.matrix(pheno)
             rownames(ph) <- rownames(expr)
             qtl2::scan1coef(genoprobs = list(probs[["{{hot_chr}}"]]), 
                             pheno = ph, 
                             kinship = K[["{{hot_chr}}"]], 
                             addcovar = covar, 
                             reml = TRUE, 
                             cores = 7
                             )
           }
                )
saveRDS(s1coef_out, fn)
}
```

```{r, get-allele-effects-{{hot_chr}}}
# add index values for peak position
local_nonlocal_annot <- dplyr::bind_rows(local_annot2, nonlocal_annot) %>%
  mutate(peak_index = match(table = names(map[["{{hot_chr}}"]]), x = marker.id)) %>%
  mutate(peak_effects = purrr::map2(.f = qtl2pleio::get_effects, .x = peak_index, .y = s1coef_out, map = map[["{{hot_chr}}"]])) %>%
  listcol_to_cols(list_column = quo(peak_effects), another_column = quo(symbol))
```



```{r, n-med-{{hot_chr}}, eval = FALSE}
n_med_tr <- 10 # arbitrary threshold for number of mediated traits per local
# only those local traits with n_med_tr or more mediated nonlocal traits 
# appear as annotation columns in the heatmap
n_med_per_local <- med_tib %>%
  group_by(local_symbol) %>%
  filter(lod_diff > 1.5) %>%
  count() %>%
  filter(n >= n_med_tr)
n_med_per_local %>%
  arrange(desc(n)) %>%
  knitr::kable(caption = "Number of mediated traits per local trait for Chr {{hot_chr}} hotspot.")
```



```{r, prepare-annotations-{{hot_chr}}}
# need 5 annotation object: 1. local v nonlocal, 2. mediation LOD difference for all local traits, 3. mediation LOD difference proportion for all local traits, 4. 8 allele effects per trait, 5. peak position per trait, encoded as binned position
# 2,3,4 are numeric; 1 & 5 are binary
## local_nonlocal_annot already has the allele effect and local v nonlocal; binning has the peak position. Need to join these two on symbol
### med_tib has lod diff & lod diff proportion for all local - nonlocal pairs
fake_tibble_mediation <- tidyr::crossing(symbol = local_annot2$symbol, 
                                         symbol2 = local_annot2$symbol) %>%
  mutate(dat = NA) %>%
  spread(key = symbol, value = dat) %>%
  rename(symbol = symbol2)
# to add to mediation tibbles  

# first med tibble
lod_diffs_tibble <- med_tib %>%
  select( - c(lod_without_med, 
              lod_with_med, 
              lod_diff_proportion, 
              local_gene_id, 
              nonlocal_gene_id)
          ) %>%
  tidyr::spread(key = local_symbol, 
                value = lod_diff) %>% 
  dplyr::rename(symbol = nonlocal_symbol) %>%
  dplyr::bind_rows(fake_tibble_mediation)
# second med tibble
lod_diff_proportions_tibble <- med_tib %>%
  select( - c(lod_without_med, 
              lod_with_med, 
              lod_diff, 
              local_gene_id, 
              nonlocal_gene_id)
          ) %>%
  tidyr::spread(key = local_symbol, 
                value = lod_diff_proportion) %>% # 147 rows by 32 columns
  rename(symbol = nonlocal_symbol) %>%
  bind_rows(fake_tibble_mediation)
# effects tibble
allele_effects_tibble <- local_nonlocal_annot %>%
  dplyr::select(symbol, 18:25)
# peak positions tibble
peak_positions <- binning %>%
  select(symbol, pos)
# local indicator
local_tibble <- local_nonlocal_annot %>%
  select(symbol, local_tx) %>% 
  ungroup()
# univariate lods
lod_tibble <- local_nonlocal_annot %>%
  select(symbol, lod) %>%
  ungroup()
```

```{r, order-annotations-{{hot_chr}}}
# all annots 
annots_ord <- list(lod_diffs_tibble, 
                   lod_diff_proportions_tibble, 
                   allele_effects_tibble,
                   peak_positions, 
                   local_tibble,
                   lod_tibble
                    ) %>% 
  purrr::map(.f = function(df, rn){
    out <- df[match(x = rn, table = df$symbol), ]
    return(out)
  }, 
  rn = rn)
```


```{r, heat-{{hot_chr}}, fig.cap="Heatmap for pleiotropy test statistics for Chr {{hot_chr}}."}
ord <- match(x = rn, table = rownames(pm))

pm[ord, ord] %>% # order both cols and rows by 'ord'
  apply(FUN = trunc2, MARGIN = 2, threshold = 5) %>%
  pheatmap::pheatmap(cluster_rows = FALSE,
                     cluster_cols = FALSE,
                     fontsize = 2,
                     annotation_row = as.data.frame(annfoo)
                     )
```



```{r, index-v-position-{{hot_chr}}, fig.cap="QTL peak position vs. dendrogram index for Chr {{hot_chr}}."}
bar <- foo %>%
  filter(local_symbol == "{{keller_mediator}}")

p <- tibble(nonlocal_symbol = rownames(pm[indic_nonlocal, ])[ord_nonlocal], index = 1:length(nonlocal_symbol)) %>%
  inner_join(bar, by = "nonlocal_symbol") %>% 
  left_join(nonlocal_annot, by = c("nonlocal_symbol" = "symbol")) %>%
  ggplot() + geom_point(aes(y = pos, x = index, color = lod_diff > 1.5, nonlocal = nonlocal_symbol, lod_diff = lod_diff)) 

ggplotly(p)
```

