# Results

We studied five expression trait hotspots in pancreatic islets from 378 Diversity Outbred mice 
[@keller2018genetic]. Scatter plots of 
pleiotropy test statistic against mediation LOD difference for local - nonlocal trait pairs reveal 
some similarities for the five hotspots. All five scatter plots have few, if any, points in the upper 
right quadrant. This tells us that local-nonlocal trait pairs may have either high pleiotropy test 
statistics or high mediation LOD differences, but not both.


Complex hotspots: Chr 5; Simple hotspots: Chr 2 (Hnf4a), Chr 13 (), Chr 7, Chr 11






We generated scatter plots of pleiotropy test statistics vs. mediation LOD difference values for each of the five hotspots (Figures).
Each point represents a pairing of a local trait with a nonlocal trait.
The mediation LOD difference value is that observed when the local trait is considered
as a candidate mediator of the QTL-nonlocal trait association.

In all five scatter plots, we observe few
points in the upper right quadrant of the figure.
That is, few pairs have high pleiotropy test statistics and
high mediation LOD difference values.


Examining the ranges of pleiotropy test statistics within a hotspot also informs our conclusions. 
Some hotspots have maximum pleiotropy test statistics under 6 (Figure \@ref(fig:scatter-7)), while 
other hotspots have local-nonlocal pairs with pleiotropy test statistics over 15 (Figure 
\@ref(fig:scatter-2)). 

Some hotspot scatter plots show points with both high pleiotropy test statistics and high mediation 
LOD differences. Closer investigation of these points reveals that, for a given hotspot, they 
include a single local trait. For example, multiple pairs with local trait *Tmem130* have high 
mediation LOD differences and high pleiotropy test statistics. This may indicate that our QTL scan 
region was too narrow to encompass the entirety of the *Tmem130* peak. 

The heatmaps reveal one of two patterns among the nonlocal traits. The first possible pattern is a 
single, mostly blue, square along the diagonal that includes most of the nonlocal traits. The second 
possible pattern involves more than one dark blue square. Chr 5 hotspot is an example of this second 
pattern. Its block-diagonal structure contains off-diagonal blocks that are a mixture of colors. 


The scatter plot of pleiotropy test statistics and mediation LOD differences reveals that few local-nonlocal 
trait pairs have both a high value of the pleiotropy test statistic and a high value of the mediation LOD 
difference. Many points have low values of both, while some points demonstrate a high value of only mediation 
LOD difference or pleiotropy test statistic. 

Many points have negative values of mediation LOD difference. These correspond to pairs that, when conditioning 
on the putative mediator, the LOD for the nonlocal trait increased. 

The points are color-coded to identify those pairs that involve the local trait *Hnf4a*, which 
@keller2018genetic identified as a key mediator of traits at this hotspot. Blue points involve *Hnf4a*, while 
red points do not. We see that many blue point have large mediation LOD differences and small pleiotropy test 
statistics. In fact, most of the points with mediation LOD difference above 15 involve *Hnf4a* and have small 
pleiotropy test statistics. 

An unanticipated observation is that some points have mediation LOD differences of 

The Chr 5 heatmap of pleiotropy test statistics 
reveals a block-diagonal pattern of blue coloring among the nonlocal traits. We observe the 
set of nonlocal traits clustered into two blocks. Within each block, any two traits share a 
QTL, ie, are pleiotropic. Yet, the off-diagonal cells, ie, those nonlocal trait pairs that 
include one trait from each of the two blocks, tend to have greater pleiotropy test 
statistics. Still, not all off-diagonal blocks have large pleiotropy test statistics. The 
mostly dark blue matrix on the diagonal (from column 22 to 99) features no cells with pleiotropy test statistics 
above 3.2. While we didn't determine p-values for these analyses, prior analyses suggest that pleiotropy test 
statistics below 3.2 are consistent with p-values above 0.05, and, thus, are consistent with a single pleiotropic 
QTL.

Columns 100 to 119 (and rows 100 to 119) are a second (symmetric) block with only small 
pleiotropy test statistics. Columns 120 to 202 contains cells for the third (symmetric) block. Column 203, the last column, contains a trait *Gm* that, based on pleiotropy test statistics, doesn't cluster near other traits.


Our analysis of the Chromosome 13 hotspot presents results much like those for the Chromosome 2 
hotspot, with the Chromosome 13 local transcript *Il6st* playing a role like that of *Hnf4a* in the 
Chr 2 hotspot. In examining the scatter plot (Figure ) of mediation LOD differences against 
pleiotropy test statistics for all local-nonlocal pairs, we see, as in Figure for the Chr 2 
hotspot, a single local trait *Il6st* has strong mediation effects on a collection of nonlocal traits. *Il6st*, first identified by @keller2018genetic, accounts for most of the nonlocal traits that are affected by the hotspot. 

The heatmap for pleiotropy statistics for pairwise tests involving nonlocal traits resembles the 
heatmap for the Chr2 hotspot. Nearly all nonlocal traits have small test statistics when paired 
with each other. This is visualized as a dark blue, symmetric square along the heatmap's diagonal 
with only a few outlier nonlocal traits that demonstrate distinct patterns in pleiotropy test 
statistics.








